version: 1
name: planners

aliases:
  "@planners": "planners"
  "@nova": "../../NovaLang/libs"

sources:
  - "planners"
  - "../../NovaLang/libs"

entries:
  - "@planners/bootstrap"

runtime:
  security: trusted-server
  thread: main
